version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: ./api.dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - "5435:5435"
    volumes:
    - db:/var/lib/postgresql/data:Z
    command: postgres -c 'max_connections=200' -p 5435

  flyway-db:
    image: boxfuse/flyway:6
    command: -url=jdbc:postgresql://db:5435/postgres -user=postgres -password=example -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/migration:/flyway/sql:Z
    depends_on:
      - db
    links:
      - db

volumes:
  db: